import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Grid,
  Paper,
  Tab,
  Tabs,
  TextField,
  Button,
  Stack,
  Divider,
  IconButton,
  Tooltip,
  Alert,
  Select,
  MenuItem,
  FormControl,
  InputLabel
} from '@mui/material';
import {
  Preview,
  Code,
  Refresh,
  Save,
  Restore,
  FullscreenExit,
  Fullscreen
} from '@mui/icons-material';
import { format } from 'date-fns';
import { fr } from 'date-fns/locale';

const EmailTemplateEditor = ({ 
  events = [], 
  projectTitle = "Project Title", 
  onTemplateChange,
  initialTemplate = null 
}) => {
  const [activeTab, setActiveTab] = useState(0);
  const [htmlContent, setHtmlContent] = useState('');
  const [previewMode, setPreviewMode] = useState(false);
  const [templateType, setTemplateType] = useState('individual'); // 'individual' or 'summary'
  const [isLoading, setIsLoading] = useState(false);
  const [sampleData, setSampleData] = useState({
    participantName: 'John Doe',
    groupName: 'Group A',
    event: events[0] || null
  });

  // Default templates
  const defaultTemplates = {
    individual: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Training Invitation - {{EVENT_TITLE}}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  
  <div style="background: linear-gradient(135deg, #1976d2 0%, #42a5f5 100%); color: white; padding: 30px; border-radius: 12px; margin-bottom: 30px; text-align: center;">
    <h1 style="margin: 0; font-size: 28px; font-weight: 700;">📅 Training Invitation</h1>
    <p style="margin: 10px 0 0 0; opacity: 0.9; font-size: 16px;">{{PROJECT_TITLE}}</p>
  </div>

  <div style="background: #ffffff; border-radius: 12px; padding: 30px; border: 1px solid #e1e5e9; margin-bottom: 20px;">
    <p style="font-size: 18px; margin-bottom: 20px;">
      Hello <strong>{{PARTICIPANT_NAME}}</strong>,
    </p>
    
    <p style="color: #6c757d; margin-bottom: 25px;">
      You are invited to attend the following training session as part of the <strong>{{GROUP_NAME}}</strong> group:
    </p>

    <div style="background-color: #f8f9fa; border-radius: 8px; padding: 20px; margin: 25px 0; border-left: 4px solid #1976d2;">
      <h2 style="margin: 0 0 15px 0; color: #1976d2; font-size: 24px;">{{EVENT_TITLE}}</h2>
      {{#COURSE_TITLE}}<p style="margin: 0 0 10px 0; color: #6c757d; font-weight: 500;">Course: {{COURSE_TITLE}}</p>{{/COURSE_TITLE}}
      
      <div style="margin: 15px 0;">
        <p style="margin: 5px 0;"><strong>📅 Date:</strong> {{EVENT_DATE}}</p>
        <p style="margin: 5px 0;"><strong>⏰ Time:</strong> {{EVENT_TIME}}</p>
        {{#EVENT_LOCATION}}<p style="margin: 5px 0;"><strong>📍 Location:</strong> {{EVENT_LOCATION}}</p>{{/EVENT_LOCATION}}
        {{#ZOOM_LINK}}
        <p style="margin: 5px 0;"><strong>💻 Join Zoom Meeting:</strong> 
          <a href="{{ZOOM_LINK}}" target="_blank" style="color: #1976d2; text-decoration: none; font-weight: 500;">
            Click to Join Meeting
          </a>
        </p>
        {{/ZOOM_LINK}}
      </div>
      
      {{#EVENT_DESCRIPTION}}
      <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid #dee2e6;">
        <p style="margin: 0; color: #6c757d;">{{EVENT_DESCRIPTION}}</p>
      </div>
      {{/EVENT_DESCRIPTION}}
    </div>

    <div style="background-color: #d4edda; border: 1px solid #c3e6cb; border-radius: 8px; padding: 16px; margin: 25px 0;">
      <h3 style="margin: 0 0 8px 0; color: #155724; font-size: 16px;">📎 Calendar Invitation Attached</h3>
      <p style="margin: 8px 0; color: #155724;">
        A calendar invitation (.ics file) is attached to this email. Click on it to add this event to your calendar.
      </p>
    </div>

    <p style="color: #6c757d; margin-top: 25px;">
      If you have any questions about this training session, please contact our training support team.
    </p>
  </div>

  <div style="text-align: center; color: #6c757d; font-size: 14px; border-top: 1px solid #e1e5e9; padding-top: 20px;">
    <p style="margin: 0;">
      Generated by EDWIND Training Management System<br>
      Please do not reply to this email.
    </p>
  </div>

</body>
</html>`,
    summary: `<!DOCTYPE html>
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en">

<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->
    <!--[if !mso]><!-->
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet" type="text/css">
    <!--<![endif]-->
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            padding: 0;
        }

        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: inherit !important;
        }

        #MessageViewBody a {
            color: inherit;
            text-decoration: none;
        }

        p {
            line-height: inherit
        }

        .desktop_hide,
        .desktop_hide table {
            mso-hide: all;
            display: none;
            max-height: 0px;
            overflow: hidden;
        }

        @media (max-width:920px) {

            .image_block img.big,
            .row-content {
                width: 100% !important;
            }

            .mobile_hide {
                display: none;
            }

            .stack .column {
                width: 100%;
                display: block;
            }

            .mobile_hide {
                min-height: 0;
                max-height: 0;
                max-width: 0;
                overflow: hidden;
                font-size: 0px;
            }

            .desktop_hide,
            .desktop_hide table {
                display: table !important;
                max-height: none !important;
            }
        }
    </style>
</head>
<body>
  <div>
    <br>
    <br>
  </div>
<div style="background-color: #ebebeb; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;">
    <table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ebebeb;">
        <tbody>
            <tr>
                <td>
                    <table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                <td class="column column-1" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 15px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td class="pad" style="width:100%;padding-right:0px;padding-left:0px;">
                                                                <div class="alignment" align="center" style="line-height:10px"><img class="big" src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/1646/top_background.png" style="display: block; height: auto; border: 0; width: 900px; max-width: 100%;" width="900" alt="Alternate text" title="Alternate text"></div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <table class="row row-2" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                <td class="column column-1" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 0px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td class="pad" style="width:100%;padding-right:0px;padding-left:0px;">
                                                                <div class="alignment" align="left" style="line-height:10px"><img src="https://d15k2d11r6t6rl.cloudfront.net/public/users/Integrators/BeeProAgency/818300_802231/sm-page-compagnie-FR-bg-copie-e1512664242473.png" style="display: block; height: auto; border: 0; width: 225px; max-width: 100%;" width="225"></div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <table class="row row-3" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                <td class="column column-1" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-left: 5px; padding-right: 5px; vertical-align: top; padding-top: 45px; padding-bottom: 25px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:5px;padding-left:30px;padding-right:30px;padding-top:5px;">
                                                                <div style="font-family: sans-serif">
                                                                    <div class style="font-size: 12px; mso-line-height-alt: 14.399999999999999px; color: #2d2d2d; line-height: 1.2; font-family: Ubuntu, Tahoma, Verdana, Segoe, sans-serif;">
                                                                        <p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 16.8px;"><span style="font-size:20px;"><strong>{{PROJECT_TITLE}}</strong></span></p>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    
                    <!-- Groups Section -->
                    {{#GROUPS_SECTION}}
                    <table class="row row-4" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                {{#GROUPS}}
                                                <td class="column column-{{GROUP_INDEX}}" width="25%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="paragraph_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:5px;padding-left:5px;padding-right:5px;padding-top:10px;">
                                                                <div style="color:#000000;direction:ltr;font-family:'Ubuntu', Tahoma, Verdana, Segoe, sans-serif;font-size:20px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:24px;">
                                                                    <p style="margin: 0;"><strong>{{GROUP_NAME}}</strong></p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table class="list_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:15px;padding-left:60px;padding-right:10px;">
                                                                {{#PARTICIPANTS}}
                                                                <ul start="1" style="margin: 0; padding: 0; margin-left: 20px; list-style-type: revert; color: #000000; direction: ltr; font-family: 'Ubuntu', Tahoma, Verdana, Segoe, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 120%; text-align: left;">
                                                                    <li style="margin-bottom: 0px;">{{PARTICIPANT_NAME}}</li>
                                                                </ul>
                                                                {{/PARTICIPANTS}}
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                {{/GROUPS}}
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    {{/GROUPS_SECTION}}

                    <!-- Schedule Days -->
                    {{#SCHEDULE_DAYS}}
                    <table class="row row-5" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                <td class="column column-1" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 20px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="divider_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:5px;padding-left:15px;padding-right:15px;padding-top:5px;">
                                                                <div class="alignment" align="center">
                                                                    <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                        <tr>
                                                                            <td class="divider_inner" style="font-size: 1px; line-height: 1px; border-top: 1px solid #2D2D2D;"><span>&#8202;</span></td>
                                                                        </tr>
                                                                    </table>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    
                    <table class="row row-6" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                <td class="column column-1" width="25%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; background-color: #ffffff; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-top:10px;">
                                                                <div style="font-family: sans-serif">
                                                                    <div class style="font-size: 12px; mso-line-height-alt: 18px; color: #2d2d2d; line-height: 1.5; font-family: Ubuntu, Tahoma, Verdana, Segoe, sans-serif;">
                                                                        <p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 21px;">{{MONTH}}</p>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad">
                                                                <div style="font-family: sans-serif">
                                                                    <div class style="font-size: 12px; mso-line-height-alt: 18px; color: #2d2d2d; line-height: 1.5; font-family: Ubuntu, Tahoma, Verdana, Segoe, sans-serif;">
                                                                        <p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 42px;"><span style="font-size:28px;"><strong>{{DAY}}</strong></span></p>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table class="text_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:10px;padding-left:5px;padding-right:5px;padding-top:5px;">
                                                                <div style="font-family: sans-serif">
                                                                    <div class style="font-size: 12px; mso-line-height-alt: 18px; color: #2d2d2d; line-height: 1.5; font-family: Ubuntu, Tahoma, Verdana, Segoe, sans-serif;">
                                                                        <p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 21px;">{{DAY_NAME}}</p>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td class="column column-2" width="50%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; background-color: #ffffff; padding-left: 15px; padding-right: 10px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="paragraph_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:5px;padding-left:5px;padding-right:5px;padding-top:10px;">
                                                                <div style="color:#cc0a0a;direction:ltr;font-family:Ubuntu, Tahoma, Verdana, Segoe, sans-serif;font-size:14px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:left;mso-line-height-alt:16.8px;">
                                                                    <p style="margin: 0;"><strong>Agenda</strong></p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    
                                                    {{#EVENTS}}
                                                    <table class="paragraph_block block-3" width="100%" border="0" cellpadding="5" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad">
                                                                <div style="color:#000000;direction:ltr;font-family:Ubuntu, Tahoma, Verdana, Segoe, sans-serif;font-size:14px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:left;mso-line-height-alt:16.8px;">
                                                                    <p style="margin: 0;"><strong>{{EVENT_TIME}}</strong> {{EVENT_TITLE}} <strong>{{EVENT_GROUPS}}</strong></p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    {{/EVENTS}}
                                                </td>
                                                <td class="column column-3" width="25%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="paragraph_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:15px;">
                                                                <div style="color:#000000;direction:ltr;font-family:Ubuntu, Tahoma, Verdana, Segoe, sans-serif;font-size:14px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:16.8px;">
                                                                    <p style="margin: 0;"><strong>Focus of the day</strong></p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table class="paragraph_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:10px;">
                                                                <div style="color:#000000;direction:ltr;font-family:Ubuntu, Tahoma, Verdana, Segoe, sans-serif;font-size:14px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:16.8px;">
                                                                    <p style="margin: 0;">Sample focus content</p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    {{/SCHEDULE_DAYS}}

                    <table class="row row-7" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                <td class="column column-1" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 0px; padding-bottom: 15px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td class="pad" style="width:100%;padding-right:0px;padding-left:0px;">
                                                                <div class="alignment" align="center" style="line-height:10px"><img class="big" src="https://d1oco4z2z1fhwp.cloudfront.net/templates/default/1646/bottom_background.png" style="display: block; height: auto; border: 0; width: 900px; max-width: 100%;" width="900" alt="Alternate text" title="Alternate text"></div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>
</body>

</html>`
  };

  // Initialize template
  useEffect(() => {
    if (initialTemplate) {
      setHtmlContent(initialTemplate);
    } else if (defaultTemplates[templateType] && !htmlContent) {
      setHtmlContent(defaultTemplates[templateType]);
    }
  }, [initialTemplate, templateType]);

  // Notify parent of template changes
  useEffect(() => {
    if (onTemplateChange) {
      onTemplateChange(htmlContent, templateType);
    }
  }, [htmlContent, templateType, onTemplateChange]);

  const handleTabChange = (event, newValue) => {
    setActiveTab(newValue);
  };

  const handleTemplateTypeChange = (event) => {
    const newType = event.target.value;
    setIsLoading(true);
    setTemplateType(newType);
    // Add a small delay to prevent flickering
    setTimeout(() => {
      setHtmlContent(defaultTemplates[newType]);
      setIsLoading(false);
    }, 100);
  };

  const handleRestoreDefault = () => {
    console.log('Restoring default template for type:', templateType);
    console.log('Default template contains SCHEDULE_DAYS?', defaultTemplates[templateType].includes('{{#SCHEDULE_DAYS}}'));
    console.log('Default template contains GROUPS_SECTION?', defaultTemplates[templateType].includes('{{#GROUPS_SECTION}}'));
    setHtmlContent(defaultTemplates[templateType]);
  };

  const renderPreview = () => {
    let previewHtml = htmlContent;
    
    // Use real project events if available, otherwise fallback to sample events for demo
    const useEvents = events && events.length > 0 ? events : [
      {
        id: 1,
        title: 'Kick-off meeting',
        course: { title: 'Management' },
        start: '2024-05-05T15:00:00',
        end: '2024-05-05T16:00:00',
        event_groups: [{ groups: { groupName: 'group 1' } }]
      },
      {
        id: 2,
        title: 'CRM sales training 1',
        course: { title: '' },
        start: '2024-05-05T16:00:00',
        end: '2024-05-05T17:00:00',
        event_groups: [{ groups: { groupName: 'group 1' } }]
      },
      {
        id: 3,
        title: 'EOD',
        start: '2024-05-05T17:00:00',
        end: '2024-05-05T18:00:00',
        event_groups: []
      },
      {
        id: 4,
        title: 'CRM sales training 1',
        course: { title: '' },
        start: '2024-05-06T09:00:00',
        end: '2024-05-06T10:00:00',
        event_groups: [{ groups: { groupName: 'group 2' } }]
      },
      {
        id: 5,
        title: 'Access verification',
        start: '2024-05-06T10:00:00',
        end: '2024-05-06T11:00:00',
        event_groups: []
      }
    ];

    console.log('Events in EmailTemplateEditor:', events);
    console.log('Using events for preview:', useEvents);
    console.log('Template type:', templateType);
    console.log('HTML content length:', htmlContent.length);
    console.log('HTML content preview:', htmlContent.substring(0, 500));
    
    // Replace template variables with sample data
    const replacements = {
      '{{PROJECT_TITLE}}': projectTitle,
      '{{PARTICIPANT_NAME}}': sampleData.participantName,
      '{{GROUP_NAME}}': sampleData.groupName,
      '{{EVENT_TITLE}}': sampleData.event?.title || useEvents[0]?.title || 'Sample Event',
      '{{COURSE_TITLE}}': sampleData.event?.course?.title || useEvents[0]?.course?.title || '',
      '{{EVENT_DATE}}': sampleData.event ? format(new Date(sampleData.event.start), 'EEEE, MMMM d, yyyy', { locale: fr }) : format(new Date(useEvents[0]?.start || '2024-05-05'), 'EEEE, MMMM d, yyyy', { locale: fr }),
      '{{EVENT_TIME}}': sampleData.event ? `${format(new Date(sampleData.event.start), 'HH:mm')} - ${format(new Date(sampleData.event.end || sampleData.event.start), 'HH:mm')}` : format(new Date(useEvents[0]?.start || '2024-05-05T15:00:00'), 'HH:mm'),
      '{{EVENT_LOCATION}}': sampleData.event?.location || 'Training Room A',
      '{{EVENT_DESCRIPTION}}': sampleData.event?.description || 'Sample event description',
      '{{ZOOM_LINK}}': 'https://us02web.zoom.us/j/123456789?pwd=example'
    };

    // Handle conditional blocks (but skip SCHEDULE_DAYS and GROUPS_SECTION)
    previewHtml = previewHtml.replace(/{{#(\w+)}}(.*?){{\/\1}}/gs, (match, variable, content) => {
      // Skip special template sections that are handled separately
      if (variable === 'SCHEDULE_DAYS' || variable === 'GROUPS_SECTION' || variable === 'GROUPS' || variable === 'EVENTS') {
        return match; // Return unchanged
      }
      const value = replacements[`{{${variable}}}`];
      return value ? content.replace(`{{${variable}}}`, value) : '';
    });

    // Replace remaining variables
    Object.entries(replacements).forEach(([variable, value]) => {
      previewHtml = previewHtml.replace(new RegExp(variable.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), value);
    });

    // Handle schedule days for summary template
    if (templateType === 'summary') {
      console.log('Processing schedule days for summary template');
      console.log('Template type is summary, checking for SCHEDULE_DAYS placeholder');
      console.log('HTML content contains SCHEDULE_DAYS?', previewHtml.includes('{{#SCHEDULE_DAYS}}'));
      console.log('HTML content contains GROUPS_SECTION?', previewHtml.includes('{{#GROUPS_SECTION}}'));
      
      // Group events by date
      const eventsByDate = useEvents.reduce((acc, event) => {
        const date = format(new Date(event.start), 'yyyy-MM-dd');
        if (!acc[date]) acc[date] = [];
        acc[date].push(event);
        return acc;
      }, {});
      
      console.log('Events grouped by date:', eventsByDate);

      const scheduleDaysHtml = Object.entries(eventsByDate).map(([dateKey, dayEvents], index, array) => {
        const date = new Date(dateKey + 'T12:00:00');
        const month = format(date, 'MMM', { locale: fr }).toUpperCase();
        const day = format(date, 'dd');
        const dayName = format(date, 'EEEE', { locale: fr }).toUpperCase();
        
        const eventsHtml = dayEvents.map(event => {
          const timeRange = format(new Date(event.start), 'HH:mm');
          const groups = event.event_groups?.map(eg => eg.groups?.groupName).filter(Boolean).join(', ');
          
          return `
            <div style="margin-bottom: 8px; font-size: 14px;">
              <strong>${timeRange}</strong> ${event.title}${event.course?.title ? ` ${event.course.title}` : ''}${groups ? ` <strong>${groups}</strong>` : ''}
            </div>
          `;
        }).join('');

        const isLastDay = index === array.length - 1;
        
        return `
          <div style="margin-bottom: 40px;">
            <div style="display: flex; align-items: flex-start; gap: 20px; margin-bottom: 20px;">
              <div style="text-align: center; min-width: 80px;">
                <div style="font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: 1px;">${month}</div>
                <div style="font-size: 32px; font-weight: bold; color: #333; line-height: 1;">${day}</div>
                <div style="font-size: 12px; color: #666; text-transform: uppercase;">${dayName}</div>
              </div>
              
              <div style="flex: 1;">
                <h3 style="color: #dc3545; font-size: 16px; font-weight: bold; margin: 0 0 15px 0;">Agenda</h3>
                ${eventsHtml}
              </div>
            </div>
            ${!isLastDay ? '<hr style="border: none; border-top: 1px solid #ddd; margin: 30px 0;">' : ''}
          </div>
        `;
      }).join('');
      
      // Generate the new HTML structure for each day
      const newScheduleDaysHtml = Object.entries(eventsByDate).map(([dateKey, dayEvents], index, array) => {
        const date = new Date(dateKey + 'T12:00:00');
        const month = format(date, 'MMM', { locale: fr }).toUpperCase();
        const day = format(date, 'dd');
        const dayName = format(date, 'EEEE', { locale: fr }).toUpperCase();
        
        const eventsHtml = dayEvents.map(event => {
          const timeRange = format(new Date(event.start), 'HH:mm');
          const groups = event.event_groups?.map(eg => eg.groups?.groupName).filter(Boolean).join(', ');
          
          return `
                                                    <table class="paragraph_block block-3" width="100%" border="0" cellpadding="5" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad">
                                                                <div style="color:#000000;direction:ltr;font-family:Ubuntu, Tahoma, Verdana, Segoe, sans-serif;font-size:14px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:left;mso-line-height-alt:16.8px;">
                                                                    <p style="margin: 0;"><strong>${timeRange}</strong> ${event.title}${event.course?.title ? ` ${event.course.title}` : ''} ${groups ? `<strong>${groups}</strong>` : ''}</p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
          `;
        }).join('');

        return `
                    <table class="row row-5" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                <td class="column column-1" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 20px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="divider_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:5px;padding-left:15px;padding-right:15px;padding-top:5px;">
                                                                <div class="alignment" align="center">
                                                                    <table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                        <tr>
                                                                            <td class="divider_inner" style="font-size: 1px; line-height: 1px; border-top: 1px solid #2D2D2D;"><span>&#8202;</span></td>
                                                                        </tr>
                                                                    </table>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    
                    <table class="row row-6" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                <td class="column column-1" width="25%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; background-color: #ffffff; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-top:10px;">
                                                                <div style="font-family: sans-serif">
                                                                    <div class style="font-size: 12px; mso-line-height-alt: 18px; color: #2d2d2d; line-height: 1.5; font-family: Ubuntu, Tahoma, Verdana, Segoe, sans-serif;">
                                                                        <p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 21px;">${month}</p>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad">
                                                                <div style="font-family: sans-serif">
                                                                    <div class style="font-size: 12px; mso-line-height-alt: 18px; color: #2d2d2d; line-height: 1.5; font-family: Ubuntu, Tahoma, Verdana, Segoe, sans-serif;">
                                                                        <p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 42px;"><span style="font-size:28px;"><strong>${day}</strong></span></p>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table class="text_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:10px;padding-left:5px;padding-right:5px;padding-top:5px;">
                                                                <div style="font-family: sans-serif">
                                                                    <div class style="font-size: 12px; mso-line-height-alt: 18px; color: #2d2d2d; line-height: 1.5; font-family: Ubuntu, Tahoma, Verdana, Segoe, sans-serif;">
                                                                        <p style="margin: 0; font-size: 14px; text-align: center; mso-line-height-alt: 21px;">${dayName}</p>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td class="column column-2" width="50%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; background-color: #ffffff; padding-left: 15px; padding-right: 10px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="paragraph_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:5px;padding-left:5px;padding-right:5px;padding-top:10px;">
                                                                <div style="color:#cc0a0a;direction:ltr;font-family:Ubuntu, Tahoma, Verdana, Segoe, sans-serif;font-size:14px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:left;mso-line-height-alt:16.8px;">
                                                                    <p style="margin: 0;"><strong>Agenda</strong></p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    ${eventsHtml}
                                                </td>
                                                <td class="column column-3" width="25%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="paragraph_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:15px;">
                                                                <div style="color:#000000;direction:ltr;font-family:Ubuntu, Tahoma, Verdana, Segoe, sans-serif;font-size:14px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:16.8px;">
                                                                    <p style="margin: 0;"><strong>Focus of the day</strong></p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table class="paragraph_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:15px;padding-left:10px;padding-right:10px;padding-top:10px;">
                                                                <div style="color:#000000;direction:ltr;font-family:Ubuntu, Tahoma, Verdana, Segoe, sans-serif;font-size:14px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:16.8px;">
                                                                    <p style="margin: 0;">Sample focus content</p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
        `;
      }).join('');
      
      console.log('Generated schedule days HTML length:', newScheduleDaysHtml.length);
      console.log('Generated schedule days HTML preview:', newScheduleDaysHtml.substring(0, 200));
      console.log('Before replacement - preview contains SCHEDULE_DAYS?', previewHtml.includes('{{#SCHEDULE_DAYS}}'));
      
      const beforeLength = previewHtml.length;
      previewHtml = previewHtml.replace(/{{#SCHEDULE_DAYS}}.*?{{\/SCHEDULE_DAYS}}/gs, newScheduleDaysHtml);
      const afterLength = previewHtml.length;
      
      console.log('After replacement - preview contains SCHEDULE_DAYS?', previewHtml.includes('{{#SCHEDULE_DAYS}}'));
      console.log('HTML length before replacement:', beforeLength, 'after:', afterLength);
      console.log('Length difference:', afterLength - beforeLength);
    }

    // Handle groups section - generate the groups HTML for the new template
    const groupsHtml = `
                                                <td class="column column-1" width="25%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="paragraph_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:5px;padding-left:5px;padding-right:5px;padding-top:10px;">
                                                                <div style="color:#000000;direction:ltr;font-family:'Ubuntu', Tahoma, Verdana, Segoe, sans-serif;font-size:20px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:24px;">
                                                                    <p style="margin: 0;"><strong>Group 1</strong></p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table class="list_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:15px;padding-left:60px;padding-right:10px;">
                                                                <ul start="1" style="margin: 0; padding: 0; margin-left: 20px; list-style-type: revert; color: #000000; direction: ltr; font-family: 'Ubuntu', Tahoma, Verdana, Segoe, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 120%; text-align: left;">
                                                                    <li style="margin-bottom: 0px;">John Doe</li>
                                                                </ul>
                                                                <ul start="1" style="margin: 0; padding: 0; margin-left: 20px; list-style-type: revert; color: #000000; direction: ltr; font-family: 'Ubuntu', Tahoma, Verdana, Segoe, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 120%; text-align: left;">
                                                                    <li style="margin-bottom: 0px;">Jane Smith</li>
                                                                </ul>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                                <td class="column column-2" width="25%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
                                                    <table class="paragraph_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:5px;padding-left:5px;padding-right:5px;padding-top:10px;">
                                                                <div style="color:#000000;direction:ltr;font-family:'Ubuntu', Tahoma, Verdana, Segoe, sans-serif;font-size:20px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:24px;">
                                                                    <p style="margin: 0;"><strong>Group 2</strong></p>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                    <table class="list_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;">
                                                        <tr>
                                                            <td class="pad" style="padding-bottom:15px;padding-left:60px;padding-right:10px;">
                                                                <ul start="1" style="margin: 0; padding: 0; margin-left: 20px; list-style-type: revert; color: #000000; direction: ltr; font-family: 'Ubuntu', Tahoma, Verdana, Segoe, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 120%; text-align: left;">
                                                                    <li style="margin-bottom: 0px;">Alice Brown</li>
                                                                </ul>
                                                                <ul start="1" style="margin: 0; padding: 0; margin-left: 20px; list-style-type: revert; color: #000000; direction: ltr; font-family: 'Ubuntu', Tahoma, Verdana, Segoe, sans-serif; font-size: 14px; font-weight: 400; letter-spacing: 0px; line-height: 120%; text-align: left;">
                                                                    <li style="margin-bottom: 0px;">Charlie Wilson</li>
                                                                </ul>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
    `;
    console.log('Before groups replacement - preview contains GROUPS?', previewHtml.includes('{{#GROUPS}}'));
    console.log('Before groups replacement - preview contains GROUPS_SECTION?', previewHtml.includes('{{#GROUPS_SECTION}}'));
    
    const beforeGroupsLength = previewHtml.length;
    previewHtml = previewHtml.replace(/{{#GROUPS}}.*?{{\/GROUPS}}/gs, groupsHtml);
    
    // Also handle the groups section wrapper
    const groupsSectionHtml = `
                    <table class="row row-4" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td>
                                    <table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 900px;" width="900">
                                        <tbody>
                                            <tr>
                                                ${groupsHtml}
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                        </tbody>
                    </table>
    `;
    previewHtml = previewHtml.replace(/{{#GROUPS_SECTION}}.*?{{\/GROUPS_SECTION}}/gs, groupsSectionHtml);
    const afterGroupsLength = previewHtml.length;
    
    console.log('After groups replacement - preview contains GROUPS?', previewHtml.includes('{{#GROUPS}}'));
    console.log('After groups replacement - preview contains GROUPS_SECTION?', previewHtml.includes('{{#GROUPS_SECTION}}'));
    console.log('Groups section length before:', beforeGroupsLength, 'after:', afterGroupsLength);

    console.log('Final preview HTML length:', previewHtml.length);
    return previewHtml;
  };

  return (
    <Box sx={{ height: '70vh', display: 'flex', flexDirection: 'column' }}>
      {/* Header */}
      <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider' }}>
        <Stack direction="row" justifyContent="space-between" alignItems="center">
          <Typography variant="h6" sx={{ fontWeight: 'bold' }}>
            Email Template Editor
          </Typography>
          
          <Stack direction="row" spacing={1} alignItems="center">
            <FormControl size="small" sx={{ minWidth: 140 }}>
              <InputLabel>Template Type</InputLabel>
              <Select
                value={templateType}
                label="Template Type"
                onChange={handleTemplateTypeChange}
              >
                <MenuItem value="individual">Individual Event</MenuItem>
                <MenuItem value="summary">Events Summary</MenuItem>
              </Select>
            </FormControl>
            
            <Tooltip title="Restore Default Template">
              <IconButton onClick={handleRestoreDefault} size="small">
                <Restore />
              </IconButton>
            </Tooltip>
            
            <Tooltip title={previewMode ? "Exit Preview" : "Toggle Preview"}>
              <IconButton onClick={() => setPreviewMode(!previewMode)} size="small">
                {previewMode ? <FullscreenExit /> : <Fullscreen />}
              </IconButton>
            </Tooltip>
          </Stack>
        </Stack>
      </Box>

      {/* Template Variables Help */}
      <Box sx={{ p: 2, backgroundColor: 'grey.50', borderBottom: 1, borderColor: 'divider' }}>
        <Typography variant="caption" color="text.secondary">
          <strong>Available Variables:</strong> {`{{PROJECT_TITLE}}, {{PARTICIPANT_NAME}}, {{GROUP_NAME}}, {{EVENT_TITLE}}, {{EVENT_DATE}}, {{EVENT_TIME}}, {{EVENT_LOCATION}}, {{COURSE_TITLE}}, {{ZOOM_LINK}}, {{EVENT_DESCRIPTION}}`}
        </Typography>
      </Box>

      {previewMode ? (
        // Full Preview Mode
        <Box sx={{ flex: 1, overflow: 'auto', p: 2 }}>
          <Paper 
            sx={{ 
              p: 2, 
              height: '100%', 
              overflow: 'auto',
              '& iframe': { width: '100%', height: '100%', border: 'none' }
            }}
          >
            <div dangerouslySetInnerHTML={{ __html: renderPreview() }} />
          </Paper>
        </Box>
      ) : (
        // Editor + Preview Split View
        <Box sx={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
          {/* Editor */}
          <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column', borderRight: 1, borderColor: 'divider' }}>
            <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
              <Tabs value={activeTab} onChange={handleTabChange}>
                <Tab 
                  icon={<Code />} 
                  label="HTML Editor" 
                  iconPosition="start"
                />
              </Tabs>
            </Box>
            
            <Box sx={{ flex: 1, p: 1, overflow: 'hidden' }}>
              <TextField
                multiline
                value={htmlContent}
                onChange={(e) => setHtmlContent(e.target.value)}
                placeholder="Enter your HTML template here..."
                sx={{ 
                  width: '100%', 
                  height: '100%',
                  '& .MuiInputBase-root': {
                    height: '100%',
                    alignItems: 'flex-start'
                  },
                  '& .MuiInputBase-input': {
                    fontFamily: 'Monaco, Consolas, "Courier New", monospace',
                    fontSize: '12px',
                    height: '100% !important',
                    overflow: 'auto !important',
                    resize: 'none'
                  },
                  '& .MuiOutlinedInput-root': {
                    height: '100%'
                  },
                  '& textarea': {
                    height: '100% !important',
                    overflow: 'auto !important'
                  }
                }}
                variant="outlined"
                InputProps={{
                  style: {
                    height: '100%',
                    overflow: 'hidden'
                  }
                }}
              />
            </Box>
          </Box>

          {/* Preview */}
          <Box sx={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
            <Box sx={{ p: 1, borderBottom: 1, borderColor: 'divider', backgroundColor: 'grey.50' }}>
              <Stack direction="row" alignItems="center" spacing={1}>
                <Preview fontSize="small" />
                <Typography variant="subtitle2">Live Preview</Typography>
                <Tooltip title="Refresh Preview">
                  <IconButton size="small" onClick={() => setActiveTab(activeTab)}>
                    <Refresh fontSize="small" />
                  </IconButton>
                </Tooltip>
              </Stack>
            </Box>
            
            <Box 
              sx={{ 
                flex: 1, 
                overflow: 'auto', 
                p: 1,
                backgroundColor: '#f5f5f5'
              }}
            >
              <Paper 
                sx={{ 
                  p: 2, 
                  height: 'fit-content',
                  minHeight: '100%',
                  overflow: 'visible',
                  transition: 'all 0.2s ease'
                }}
              >
                {isLoading ? (
                  <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '200px' }}>
                    <Typography variant="body2" color="text.secondary">Loading template...</Typography>
                  </Box>
                ) : (
                  <div 
                    dangerouslySetInnerHTML={{ __html: renderPreview() }}
                    style={{ transition: 'opacity 0.2s ease' }}
                  />
                )}
              </Paper>
            </Box>
          </Box>
        </Box>
      )}

    </Box>
  );
};

export default EmailTemplateEditor;